services:
- name: aggregate-healthcheck-sidekick@.service
  count: 1
- name: aggregate-healthcheck@.service
  count: 1
- name: api-policy-component@.service
  version: v20
  count: 2
- name: api-policy-component-sidekick@.service
  count: 2
- name: binary-ingester-sidekick@.service
  count: 2
- name: binary-ingester@.service
  version: v77
  count: 2
- name: binary-writer-sidekick@.service
  count: 2
- name: binary-writer@.service
  version: v43
  count: 2
- name: cms-notifier-sidekick@.service
  count: 2
- name: cms-notifier@.service
  version: v29
  count: 2
- name: cms-kafka-bridge-sidekick@.service
  count: 2
- name: cms-kafka-bridge@.service
  version: v9
  count: 2
- name: cms-metadata-kafka-bridge-sidekick@.service
  count: 2
- name: cms-metadata-kafka-bridge@.service
  version: v9
  count: 2
- name: concept-suggestions-kafka-bridge-sidekick@.service
  count: 2
- name: concept-suggestions-kafka-bridge@.service
  version: v9
  count: 2
- name: content-ingester-sidekick@.service
  count: 2
- name: content-ingester@.service
  version: v34
  count: 2
- name: content-preview@.service
  count: 2
- name: content-preview-sidekick@.service
  count: 2
- name: content-public-read-preview-sidekick@.service
  count: 2
- name: content-public-read-preview@.service
  count: 2
- name: content-public-read-preview-sidekick@.service
  count: 2
- name: content-public-read-preview@.service
  count: 2
- name: diamond.service
- name: document-store-api-sidekick@.service
  count: 2
- name: document-store-api@.service
  version: v34
  count: 2
- name: elb-dns-registrator.service
  version: v2.0.0
- name: elb-presence.service
- name: fleet-unit-healthcheck-sidekick.service
- name: fleet-unit-healthcheck.service
- name: image-cleaner.service
- name: kafka-rest-proxy-sidekick.service
- name: kafka-rest-proxy.service
- name: kafka.service
- name: methode-article-transformer-sidekick@.service
  count: 2
- name: methode-article-transformer@.service
  count: 2
- name: methode-content-importer-sidekick@.service
  count: 2
- name: methode-content-importer@.service
  version: v41
  count: 2
- name: methode-image-binary-transformer-sidekick@.service
  count: 2
- name: methode-image-binary-transformer@.service
  version: v21
  count: 2
- name: methode-image-model-transformer-sidekick@.service
  count: 2
- name: methode-image-model-transformer@.service
  version: v37
  count: 2
- name: methode-list-transformer-sidekick@.service
  count: 2
- name: methode-list-transformer@.service
  version: v9
  count: 2
- name: methodeapi-endpoint.service
- name: mongo-backup.service
  desiredState: loaded
- name: mongo-backup.timer
- name: mongodb-all.service
- name: mongodb-configurator.service
- name: mongodb-sidekick@.service
  count: 3
- name: mongodb@.service
  count: 3
- name: nativerw-sidekick@.service
  count: 2
- name: nativerw@.service
  version: v35
  count: 2
- name: neo4j@.service
  count: 1
- name: neo4j-sidekick@.service
  count: 1
- name: notifications-ingester-sidekick@.service
  count: 2
- name: notifications-ingester@.service
  version: v34
  count: 2
- name: notifications-rw-sidekick@.service
  count: 2
- name: notifications-rw@.service
  version: v30
  count: 2
- name: publish-availability-monitor-sidekick@.service
  count: 1
- name: publish-availability-monitor@.service
  version: v0.16.3
  count: 1
- name: restorage-mongo-sidekick@.service
  count: 1
- name: restorage-mongo@.service
  count: 1
- name: splunk-forwarder.service
- name: synthetic-image-publication-monitor-aws-sidekick@.service
  count: 1
- name: synthetic-image-publication-monitor-aws@.service
  version: v33
  count: 1
- name: synthetic-image-publication-monitor-coco-sidekick@.service
  count: 1
- name: synthetic-image-publication-monitor-coco@.service
  version: v33
  count: 1
- name: synthetic-publication-monitor-sidekick@.service
  count: 1
- name: synthetic-publication-monitor@.service
  count: 1
- name: system-healthcheck-sidekick.service
- name: system-healthcheck.service
- name: tunnel-registrator.service
- name: varnish-sidekick@.service
  count: 2
- name: varnish@.service
  version: v35
  count: 2
- name: vulcan-config-builder.service
  version: v5
- name: vulcan.service
- name: wordpress-article-transformer-sidekick@.service
  count: 2
- name: wordpress-article-transformer@.service
  version: v46
  count: 2
- name: zookeeper.service
