services:
- name: aggregate-healthcheck-sidekick@.service
  count: 2
- name: aggregate-healthcheck@.service
  version: v1.1.5
  count: 2
  sequentialDeployment: true
- name: alphaville-series-rw-neo4j-blue-sidekick@.service
  count: 1
- name: alphaville-series-rw-neo4j-blue@.service
  version: v0.0.8
  count: 1
- name: alphaville-series-rw-neo4j-red-sidekick@.service
  count: 1
- name: alphaville-series-rw-neo4j-red@.service
  version: v0.0.8
  count: 1
- name: api-policy-component-sidekick@.service
  count: 2
- name: api-policy-component@.service
  version: v56
  count: 2
  sequentialDeployment: true
- name: binary-ingester-sidekick@.service
  count: 2
- name: binary-ingester@.service
  version: v92
  count: 2
- name: binary-writer-sidekick@.service
  count: 2
- name: binary-writer@.service
  version: v48
  count: 2
- name: brands-rw-neo4j-blue-sidekick@.service
  count: 1
- name: brands-rw-neo4j-blue@.service
  version: v0.1.3
  count: 1
- name: brands-rw-neo4j-red-sidekick@.service
  count: 1
- name: brands-rw-neo4j-red@.service
  version: v0.1.3
  count: 1
  sequentialDeployment: true
- name: cms-kafka-bridge-pub-pre-prod-sidekick@.service
  count: 2
- name: cms-kafka-bridge-pub-pre-prod@.service
  version: v13.0.0
  count: 2
- name: cms-kafka-bridge-pub-prod-sidekick@.service
  count: 2
- name: cms-kafka-bridge-pub-prod@.service
  version: v13.0.0
  count: 2
- name: cms-kafka-bridge-ucs-test-sidekick@.service
  count: 2
- name: cms-kafka-bridge-ucs-test@.service
  version: v13.0.0
  count: 2
- name: cms-metadata-kafka-bridge-pub-pre-prod-sidekick@.service
  count: 2
- name: cms-metadata-kafka-bridge-pub-pre-prod@.service
  version: v13.0.0
  count: 2
- name: cms-metadata-kafka-bridge-pub-prod-sidekick@.service
  count: 2
- name: cms-metadata-kafka-bridge-pub-prod@.service
  version: v13.0.0
  count: 2
- name: cms-metadata-kafka-bridge-ucs-test-sidekick@.service
  count: 2
- name: cms-metadata-kafka-bridge-ucs-test@.service
  version: v13.0.0
  count: 2
- name: cms-notifier-sidekick@.service
  count: 1
- name: cms-notifier@.service
  version: v33
  count: 1
- name: concept-ingester-blue-sidekick@.service
  count: 1
- name: concept-ingester-blue@.service
  version: v1.1.7
  count: 1
- name: concept-ingester-red-sidekick@.service
  count: 1
- name: concept-ingester-red@.service
  version: v1.1.7
  count: 1
- name: concept-suggestions-kafka-bridge-sidekick@.service
  count: 2
- name: concept-suggestions-kafka-bridge-ucs-test-sidekick@.service
  count: 2
- name: concept-suggestions-kafka-bridge-ucs-test@.service
  version: v13.0.0
  count: 2
- name: concept-suggestions-kafka-bridge@.service
  version: v13.0.0
  count: 2
- name: concepts-kafka-bridge-pub-pre-prod-sidekick@.service
  count: 1
- name: concepts-kafka-bridge-pub-pre-prod@.service
  version: v13.0.0
  count: 1
- name: content-ingester-neo4j-blue-sidekick@.service
  count: 1
- name: content-ingester-neo4j-blue@.service
  version: v50
  count: 1
- name: content-ingester-neo4j-red-sidekick@.service
  count: 1
- name: content-ingester-neo4j-red@.service
  version: v50
  count: 1
- name: content-ingester-sidekick@.service
  count: 2
- name: content-ingester@.service
  version: v50
  count: 2
- name: content-preview-sidekick@.service
  count: 2
- name: content-preview@.service
  version: v0.0.4
  count: 2
  sequentialDeployment: true
- name: content-public-read-preview-sidekick@.service
  count: 2
- name: content-public-read-preview@.service
  version: v51
  count: 2
  sequentialDeployment: true
- name: content-public-read-sidekick@.service
  count: 2
- name: content-public-read@.service
  version: v51
  count: 2
  sequentialDeployment: true
- name: content-rw-neo4j-blue-sidekick@.service
  count: 1
- name: content-rw-neo4j-blue@.service
  version: v0.0.36
  count: 1
- name: content-rw-neo4j-red-sidekick@.service
  count: 1
- name: content-rw-neo4j-red@.service
  version: v0.0.36
  count: 1
- name: coreos-version-checker-sidekick.service
- name: coreos-version-checker.service
  version: v1.0.0
- name: diamond.service
- name: document-store-api-sidekick@.service
  count: 2
- name: document-store-api@.service
  version: v82
  count: 2
  sequentialDeployment: true
- name: elasticsearch-sidekick.service
- name: elasticsearch.service
- name: elb-dns-registrator.service
  version: v4.0.0
- name: elb-presence@.service
  count: 2
- name: enriched-content-read-api-sidekick@.service
  count: 2
- name: enriched-content-read-api@.service
  version: v67
  count: 2
  sequentialDeployment: true
- name: financial-instruments-rw-neo4j-blue-sidekick@.service
  count: 1
- name: financial-instruments-rw-neo4j-blue@.service
  version: v0.0.1
  count: 1
- name: financial-instruments-rw-neo4j-red-sidekick@.service
  count: 1
- name: financial-instruments-rw-neo4j-red@.service
  version: v0.0.1
  count: 1
- name: fleet-unit-healthcheck-sidekick@.service
  count: 1
- name: fleet-unit-healthcheck@.service
  version: 1.0.8
  count: 1
- name: genres-rw-neo4j-blue-sidekick@.service
  count: 1
- name: genres-rw-neo4j-blue@.service
  version: v1.1.5
  count: 1
- name: genres-rw-neo4j-red-sidekick@.service
  count: 1
- name: genres-rw-neo4j-red@.service
  version: v1.1.5
  count: 1
- name: image-cleaner.service
  version: 1.0.0
- name: industry-classifications-rw-neo4j-blue-sidekick@.service
  count: 1
- name: industry-classifications-rw-neo4j-blue@.service
  version: v0.0.6
  count: 1
- name: industry-classifications-rw-neo4j-red-sidekick@.service
  count: 1
- name: industry-classifications-rw-neo4j-red@.service
  version: v0.0.6
  count: 1
- name: kafka-rest-proxy-sidekick@.service
  count: 1
- name: kafka-rest-proxy@.service
  version: v1.0.0
  count: 1
- name: kafka.service
- name: locations-rw-neo4j-blue-sidekick@.service
  count: 1
- name: locations-rw-neo4j-blue@.service
  version: v1.1.3
  count: 1
- name: locations-rw-neo4j-red-sidekick@.service
  count: 1
- name: locations-rw-neo4j-red@.service
  version: v1.1.3
  count: 1
- name: memberships-rw-neo4j-blue-sidekick@.service
  count: 1
- name: memberships-rw-neo4j-blue@.service
  version: v0.1.4
  count: 1
- name: memberships-rw-neo4j-red-sidekick@.service
  count: 1
- name: memberships-rw-neo4j-red@.service
  version: v0.1.4
  count: 1
- name: methode-article-transformer-sidekick@.service
  count: 2
- name: methode-article-transformer@.service
  version: v82
  count: 2
- name: methode-content-importer-sidekick@.service
  count: 2
- name: methode-content-importer@.service
  version: v56
  count: 2
- name: methode-image-binary-transformer-sidekick@.service
  count: 2
- name: methode-image-binary-transformer@.service
  version: v24
  count: 2
- name: methode-image-model-transformer-sidekick@.service
  count: 2
- name: methode-image-model-transformer@.service
  version: v46
  count: 2
- name: methode-list-transformer-sidekick@.service
  count: 2
- name: methode-list-transformer@.service
  version: v31
  count: 2
- name: mongo-backup@.service
  version: v20.0.0
  count: 3
  desiredState: loaded
- name: mongo-backup@.timer
  count: 3
- name: mongodb-configurator.service
- name: mongodb-online-backup.service
  version: v0.1.0
  desiredState: loaded
- name: mongodb-sidekick@.service
  count: 3
- name: mongodb@.service
  count: 3
  sequentialDeployment: true
- name: nativerw-sidekick@.service
  count: 2
- name: nativerw@.service
  version: v1.1.0
  count: 2
  sequentialDeployment: true
- name: neo4j-backup.service
  version: 0.8.1
  desiredState: inactive
- name: neo4j-blue-sidekick@.service
  count: 1
- name: neo4j-blue@.service
  version: 2.3.7-2
  count: 1
- name: neo4j-hot-backup@.service
  version: 1.1-go
  count: 1
- name: neo4j-hot-backup@.timer
  count: 1
- name: neo4j-read-blue-sidekick@.service
  count: 1
- name: neo4j-read-red-sidekick@.service
  count: 1
- name: neo4j-red-sidekick@.service
  count: 1
- name: neo4j-red@.service
  version: 2.3.7-2
  count: 1
- name: notifications-ingester-sidekick@.service
  count: 2
- name: notifications-ingester@.service
  version: v50
  count: 2
- name: notifications-push-sidekick@.service
  count: 2
- name: notifications-push@.service
  version: v2.4.17
  count: 2
  sequentialDeployment: true
- name: notifications-rw-sidekick@.service
  count: 2
- name: notifications-rw@.service
  version: v53
  count: 2
  sequentialDeployment: true
- name: organisations-rw-neo4j-blue-sidekick@.service
  count: 1
- name: organisations-rw-neo4j-blue@.service
  version: v0.3.1
  count: 1
- name: organisations-rw-neo4j-red-sidekick@.service
  count: 1
- name: organisations-rw-neo4j-red@.service
  version: v0.3.1
  count: 1
- name: os-upgrade.service
  desiredState: loaded
- name: people-rw-neo4j-blue-sidekick@.service
  count: 1
- name: people-rw-neo4j-blue@.service
  version: v0.1.3
  count: 1
- name: people-rw-neo4j-red-sidekick@.service
  count: 1
- name: people-rw-neo4j-red@.service
  version: v0.1.3
  count: 1
- name: public-annotations-api-sidekick@.service
  count: 2
- name: public-annotations-api@.service
  version: v0.0.16
  count: 2
  sequentialDeployment: true
- name: public-brands-api-sidekick@.service
  count: 2
- name: public-brands-api@.service
  version: v0.0.8
  count: 2
  sequentialDeployment: true
- name: public-concordances-api-sidekick@.service
  count: 2
- name: public-concordances-api@.service
  version: v0.1.5
  count: 2
  sequentialDeployment: true
- name: public-content-by-concept-api-sidekick@.service
  count: 2
- name: public-content-by-concept-api@.service
  version: v0.0.10
  count: 2
  sequentialDeployment: true
- name: public-organisations-api-sidekick@.service
  count: 2
- name: public-organisations-api@.service
  version: v0.1.0
  count: 2
  sequentialDeployment: true
- name: public-people-api-sidekick@.service
  count: 2
- name: public-people-api@.service
  version: v0.1.3
  count: 2
  sequentialDeployment: true
- name: public-six-degrees-sidekick@.service
  count: 2
- name: public-six-degrees@.service
  version: 0.0.6
  count: 2
  sequentialDeployment: true
- name: public-things-api-sidekick@.service
  count: 2
- name: public-things-api@.service
  version: 0.0.16
  count: 2
  sequentialDeployment: true
- name: publish-availability-monitor-sidekick@.service
  count: 1
- name: publish-availability-monitor@.service
  version: v0.20.1
  count: 1
- name: restorage-elasticsearch-concepts-sidekick@.service
  count: 1
- name: restorage-elasticsearch-concepts@.service
  version: v0.0.3
  count: 1
- name: restorage-mongo-native-sidekick@.service
  count: 1
- name: restorage-mongo-native@.service
  count: 1
- name: restorage-mongo-sidekick@.service
  count: 1
- name: restorage-mongo@.service
  count: 1
- name: roles-rw-neo4j-blue-sidekick@.service
  count: 1
- name: roles-rw-neo4j-blue@.service
  version: v0.1.4
  count: 1
- name: roles-rw-neo4j-red-sidekick@.service
  count: 1
- name: roles-rw-neo4j-red@.service
  version: v0.1.4
  count: 1
- name: sections-rw-neo4j-blue-sidekick@.service
  count: 1
- name: sections-rw-neo4j-blue@.service
  version: v1.1.3
  count: 1
- name: sections-rw-neo4j-red-sidekick@.service
  count: 1
- name: sections-rw-neo4j-red@.service
  version: v1.1.3
  count: 1
- name: special-reports-rw-neo4j-blue-sidekick@.service
  count: 1
- name: special-reports-rw-neo4j-blue@.service
  version: v1.1.3
  count: 1
- name: special-reports-rw-neo4j-red-sidekick@.service
  count: 1
- name: special-reports-rw-neo4j-red@.service
  version: v1.1.3
  count: 1
- name: splunk-forwarder.service
- name: subjects-rw-neo4j-blue-sidekick@.service
  count: 1
- name: subjects-rw-neo4j-blue@.service
  version: v1.1.2
  count: 1
- name: subjects-rw-neo4j-red-sidekick@.service
  count: 1
- name: subjects-rw-neo4j-red@.service
  version: v1.1.2
  count: 1
- name: synthetic-image-publication-monitor-coco-sidekick@.service
  count: 1
- name: synthetic-image-publication-monitor-coco@.service
  version: v36
  count: 1
- name: system-healthcheck-sidekick.service
- name: system-healthcheck.service
  version: 1.0.3
- name: topics-rw-neo4j-blue-sidekick@.service
  count: 1
- name: topics-rw-neo4j-blue@.service
  version: v1.1.3
  count: 1
- name: topics-rw-neo4j-red-sidekick@.service
  count: 1
- name: topics-rw-neo4j-red@.service
  version: v1.1.3
  count: 1
- name: tunnel-registrator.service
  version: 1.0.0
- name: up-coco-admin-sidekick@.service
  count: 1
- name: up-coco-admin@.service
  version: v0.0.2
  count: 1
- name: up-queue-sender-v1-metadata-sidekick@.service
  count: 1
- name: up-queue-sender-v1-metadata@.service
  version: v0.0.2
  count: 1
- name: v1-annotations-rw-blue-sidekick@.service
  count: 1
- name: v1-annotations-rw-blue@.service
  version: v0.1.0
  count: 1
- name: v1-annotations-rw-red-sidekick@.service
  count: 1
- name: v1-annotations-rw-red@.service
  version: v0.1.0
  count: 1
- name: v1-content-annotator-binding-service-blue-sidekick@.service
  count: 1
- name: v1-content-annotator-binding-service-blue@.service
  version: v25
  count: 1
- name: v1-content-annotator-binding-service-red-sidekick@.service
  count: 1
- name: v1-content-annotator-binding-service-red@.service
  version: v25
  count: 1
- name: v1-content-annotator-blue-sidekick@.service
  count: 1
- name: v1-content-annotator-blue@.service
  version: v25
  count: 1
- name: v1-content-annotator-brightcove-blue-sidekick@.service
  count: 1
- name: v1-content-annotator-brightcove-blue@.service
  version: v25
  count: 1
- name: v1-content-annotator-brightcove-red-sidekick@.service
  count: 1
- name: v1-content-annotator-brightcove-red@.service
  version: v25
  count: 1
- name: v1-content-annotator-red-sidekick@.service
  count: 1
- name: v1-content-annotator-red@.service
  version: v25
  count: 1
- name: v1-suggestor-sidekick@.service
  count: 2
- name: v1-suggestor@.service
  version: v0.0.14
  count: 2
- name: v2-annotations-rw-blue-sidekick@.service
  count: 1
- name: v2-annotations-rw-blue@.service
  version: v0.1.0
  count: 1
- name: v2-annotations-rw-red-sidekick@.service
  count: 1
- name: v2-annotations-rw-red@.service
  version: v0.1.0
  count: 1
- name: v2-content-annotator-blue-sidekick@.service
  count: 1
- name: v2-content-annotator-blue@.service
  version: v24
  count: 1
- name: v2-content-annotator-red-sidekick@.service
  count: 1
- name: v2-content-annotator-red@.service
  version: v24
  count: 1
- name: varnish@.service
  version: v75
  count: 2
  sequentialDeployment: true
- name: video-mapper-sidekick@.service
  count: 2
- name: video-mapper@.service
  version: v1.2.9
  count: 2
- name: vulcan-config-builder.service
  version: v1.3.2
- name: vulcan.service
  version: v1.2.2
- name: wordpress-article-transformer-sidekick@.service
  count: 2
- name: wordpress-article-transformer@.service
  version: v90
  count: 2
- name: wordpress-image-mapper-sidekick@.service
  count: 2
- name: wordpress-image-mapper@.service
  version: v32
  count: 2
- name: zookeeper.service
