services:
- name: aggregate-healthcheck-sidekick@.service
  count: 1
- name: aggregate-healthcheck@.service
  version: v1.0.6
  count: 1
- name: api-policy-component-sidekick@.service
  count: 2
- name: api-policy-component@.service
  version: v24
  count: 2
  sequentialDeployment: true
- name: binary-ingester-sidekick@.service
  count: 2
- name: binary-ingester@.service
  version: v87
  count: 2
  sequentialDeployment: true
- name: binary-writer-sidekick@.service
  count: 2
- name: binary-writer@.service
  version: v47
  count: 2
- name: cms-kafka-bridge-sidekick@.service
  count: 2
- name: cms-kafka-bridge@.service
  version: v9
  count: 2
- name: cms-metadata-kafka-bridge-sidekick@.service
  count: 2
- name: cms-metadata-kafka-bridge@.service
  version: v9
  count: 2
- name: cms-notifier-sidekick@.service
  count: 1
- name: cms-notifier@.service
  version: v32
  count: 1
- name: concept-suggestions-kafka-bridge-sidekick@.service
  count: 2
- name: concept-suggestions-kafka-bridge@.service
  version: v9
  count: 2
- name: content-ingester-neo4j-red-sidekick@.service
  count: 1
- name: content-ingester-neo4j-red@.service
  version: v34
  count: 1
- name: content-ingester-neo4j-sidekick@.service
  count: 2
- name: content-ingester-neo4j@.service
  version: v34
  count: 2
- name: content-ingester-sidekick@.service
  count: 2
- name: content-ingester@.service
  version: v34
  count: 2
- name: content-preview-sidekick@.service
  count: 2
- name: content-preview@.service
  version: v0.0.3
  count: 2
- name: content-public-read-preview-sidekick@.service
  count: 2
- name: content-public-read-preview@.service
  version: v36
  count: 2
- name: content-rw-neo4j-red-sidekick@.service
  count: 2
- name: content-rw-neo4j-red@.service
  version: v0.0.23
  count: 2
- name: content-rw-neo4j-sidekick@.service
  count: 2
- name: content-rw-neo4j@.service
  version: v0.0.25
  count: 2
- name: diamond.service
- name: document-store-api-sidekick@.service
  count: 2
- name: document-store-api@.service
  version: v45
  count: 2
  sequentialDeployment: true
- name: elb-dns-registrator.service
  version: v2.0.1
- name: elb-presence@.service
  count: 2
- name: enriched-content-read-api-sidekick@.service
  count: 2
- name: enriched-content-read-api@.service
  version: v51
  count: 2
  sequentialDeployment: true
- name: fleet-unit-healthcheck-sidekick.service
- name: fleet-unit-healthcheck.service
- name: genres-rw-neo4j-red-sidekick@.service
  count: 1
- name: genres-rw-neo4j-red@.service
  version: v1.0.0
  count: 1
- name: genres-rw-neo4j-sidekick@.service
  count: 1
- name: genres-rw-neo4j@.service
  version: v1.0.0
  count: 1
- name: image-cleaner.service
- name: kafka-rest-proxy-sidekick.service
- name: kafka-rest-proxy.service
- name: kafka.service
- name: locations-rw-neo4j-red-sidekick@.service
  count: 2
- name: locations-rw-neo4j-red@.service
  version: v1.0.0
  count: 2
- name: locations-rw-neo4j-sidekick@.service
  count: 2
- name: locations-rw-neo4j@.service
  version: v1.0.0
  count: 2
- name: locations-transformer-sidekick@.service
  count: 2
- name: locations-transformer@.service
  version: v1.0.0
  count: 2
- name: methode-article-transformer-sidekick@.service
  count: 2
- name: methode-article-transformer@.service
  version: v39
  count: 2
- name: methode-content-importer-sidekick@.service
  count: 2
- name: methode-content-importer@.service
  version: v41
  count: 2
- name: methode-image-binary-transformer-sidekick@.service
  count: 2
- name: methode-image-binary-transformer@.service
  version: v23
  count: 2
- name: methode-image-model-transformer-sidekick@.service
  count: 2
- name: methode-image-model-transformer@.service
  version: v43
  count: 2
- name: methode-list-transformer-sidekick@.service
  count: 2
- name: methode-list-transformer@.service
  version: v13
  count: 2
- name: methodeapi-endpoint.service
- name: mongo-backup.service
  desiredState: loaded
- name: mongo-backup.timer
- name: mongodb-all.service
- name: mongodb-configurator.service
- name: mongodb-sidekick@.service
  count: 3
- name: mongodb@.service
  count: 3
- name: native-ingester-metadata-sidekick@.service
  count: 2
- name: native-ingester-metadata@.service
  version: v0.0.2
  count: 2
- name: nativerw-sidekick@.service
  count: 2
- name: nativerw@.service
  version: v37
  count: 2
- name: neo4j-red-sidekick@.service
  count: 1
- name: neo4j-red@.service
  count: 1
- name: neo4j-sidekick@.service
  count: 1
- name: neo4j@.service
  count: 1
- name: notifications-ingester-sidekick@.service
  count: 2
- name: notifications-ingester@.service
  version: v34
  count: 2
- name: notifications-rw-sidekick@.service
  count: 2
- name: notifications-rw@.service
  version: v30
  count: 2
- name: people-rw-neo4j-red-sidekick@.service
  count: 2
- name: people-rw-neo4j-red@.service
  version: v0.0.54
  count: 2
- name: people-rw-neo4j-sidekick@.service
  count: 2
- name: people-rw-neo4j@.service
  version: v0.0.54
  count: 2
- name: public-annotations-api-sidekick@.service
  count: 2
- name: public-annotations-api@.service
  version: v0.0.4
  count: 2
  sequentialDeployment: true
- name: public-people-api-sidekick@.service
  count: 2
- name: public-people-api@.service
  version: v0.0.64
  count: 2
- name: public-things-api-sidekick@.service
  count: 2
- name: public-things-api@.service
  version: v1.0.4
  count: 2
  sequentialDeployment: true
- name: publish-availability-monitor-sidekick@.service
  count: 1
- name: publish-availability-monitor@.service
  version: v0.16.3
  count: 1
- name: public-organisations-api-sidekick@.service
  count: 2
- name: public-organisations-api@.service
  version: v0.0.41
  count: 2
  sequentialDeployment: true
- name: restorage-mongo-sidekick@.service
  count: 1
- name: restorage-mongo@.service
  count: 1
- name: sections-rw-neo4j-red-sidekick@.service
  count: 2
- name: sections-rw-neo4j-red@.service
  version: v1.0.1
  count: 2
- name: sections-rw-neo4j-sidekick@.service
  count: 2
- name: sections-rw-neo4j@.service
  version: v1.0.1
  count: 2
- name: sections-transformer-sidekick@.service
  count: 2
- name: sections-transformer@.service
  version: v1.0.0
  count: 2
- name: splunk-forwarder.service
- name: subjects-rw-neo4j-red-sidekick@.service
  count: 2
- name: subjects-rw-neo4j-red@.service
  version: v1.0.3
  count: 2
- name: subjects-rw-neo4j-sidekick@.service
  count: 2
- name: subjects-rw-neo4j@.service
  version: v1.0.3
  count: 2
- name: subjects-transformer-sidekick@.service
  count: 2
- name: subjects-transformer@.service
  version: v1.0.0
  count: 2
- name: synthetic-image-publication-monitor-aws-sidekick@.service
  count: 1
- name: synthetic-image-publication-monitor-aws@.service
  version: v36
  count: 1
- name: synthetic-image-publication-monitor-coco-sidekick@.service
  count: 1
- name: synthetic-image-publication-monitor-coco@.service
  version: v36
  count: 1
- name: system-healthcheck-sidekick.service
- name: system-healthcheck.service
- name: topics-rw-neo4j-red-sidekick@.service
  count: 2
- name: topics-rw-neo4j-red@.service
  version: v1.0.0
  count: 2
- name: topics-rw-neo4j-sidekick@.service
  count: 2
- name: topics-rw-neo4j@.service
  version: v1.0.0
  count: 2
- name: topics-transformer-sidekick@.service
  count: 2
- name: topics-transformer@.service
  version: v1.0.0
  count: 2
- name: tunnel-registrator.service
- name: v1-annotations-rw-red-sidekick@.service
  count: 2
- name: v1-annotations-rw-red@.service
  version: v0.0.12
  count: 2
- name: v1-annotations-rw-sidekick@.service
  count: 2
- name: v1-annotations-rw@.service
  version: v0.0.12
  count: 2
- name: v1-content-annotator-red-sidekick@.service
  count: 1
- name: v1-content-annotator-red@.service
  version: v22
  count: 1
- name: v1-content-annotator-sidekick@.service
  count: 2
- name: v1-content-annotator@.service
  version: v22
  count: 2
- name: v1-suggestor-sidekick@.service
  count: 2
- name: v1-suggestor@.service
  version: v0.0.7
  count: 2
- name: v2-annotations-rw-red-sidekick@.service
  count: 2
- name: v2-annotations-rw-red@.service
  version: v0.0.12
  count: 2
- name: v2-annotations-rw-sidekick@.service
  count: 2
- name: v2-annotations-rw@.service
  version: v0.0.12
  count: 2
- name: v2-content-annotator-red-sidekick@.service
  count: 1
- name: v2-content-annotator-red@.service
  version: v22
  count: 1
- name: v2-content-annotator-sidekick@.service
  count: 2
- name: v2-content-annotator@.service
  version: v22
  count: 2
- name: varnish-sidekick@.service
  count: 2
- name: varnish@.service
  version: v44
  count: 2
  sequentialDeployment: true
- name: vulcan-config-builder.service
  version: v1.0.6
- name: vulcan.service
  version: v1.1.0
- name: wordpress-article-transformer-sidekick@.service
  count: 2
- name: wordpress-article-transformer@.service
  version: v46
  count: 2
- name: zookeeper.service
